logging:
  level:
    root: info
server:
  port: 8082
spring:
  application:
    name: transcation-service-A
  datasource: #连接池类型配置
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: meng5351
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transactionA?useUnicode=true&characterEncoding=utf-8
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 30000
      maxLifetime: 1800000
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  config-location: classpath:mybatis-config.xml
dubbo:
  scan:
    base-packages: io.mlc.transaction.serivce.service
  protocol:
    name: dubbo #dubbo服务使用协议名称
    port: 20880 #dubbo服务提供端口号
  registry:
    address:  zookeeper://localhost:2181 #注册中心地址
  metadata-report:
    address: zookeeper://localhost:2181 #元数据中心地址

