server:
  port: 8081
  servlet:
    context-path: /
logging:
  level:
    root: INFO
spring:
  redis:
    sentinel:
      master: master
      nodes:
        - 127.0.0.1:26379
        - 127.0.0.1:26380
        - 127.0.0.1:26381